server:
  port: 18080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wisdom?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: adminuser